Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,85 +9,91 @@ permissions:
 
 jobs:
   inspect-code:
-      name: Code Quality
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout
-          uses: actions/checkout@v3
+    name: Code Quality
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-        - name: Install .NET 3.1.x LTS
-          uses: actions/setup-dotnet@v3
-          with:
-            dotnet-version: "3.1.x"
+      - name: Install .NET 8.0.x
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: "8.0.x"
 
-        - name: Install .NET 6.0.x
-          uses: actions/setup-dotnet@v3
-          with:
-            dotnet-version: "6.0.x"
+      - name: Restore Tools
+        run: dotnet tool restore
 
-        - name: Restore Tools
-          run: dotnet tool restore
+      - name: Restore Packages
+        run: dotnet restore Circle.Desktop.slnf
 
-        - name: Restore Packages
-          run: dotnet restore Circle.Desktop.slnf
+      - name: Restore inspectcode cache
+        uses: actions/cache@v4
+        with:
+          path: ${{ github.workspace }}/inspectcode
+          key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'Circle.sln*', 'Circle*.slnf', '.editorconfig', '.globalconfig', 'CodeAnalysis/*', '**/*.csproj', '**/*.props') }}
 
-        - name: Restore inspectcode cache
-          uses: actions/cache@v3
-          with:
-            path: ${{ github.workspace }}/inspectcode
-            key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'Circle.sln*', 'Circle*.slnf', '.editorconfig', '.globalconfig', 'CodeAnalysis/*', '**/*.csproj', '**/*.props') }}
+      - name: Dotnet code style
+        run: dotnet build -c Debug -warnaserror Circle.Desktop.slnf -p:EnforceCodeStyleInBuild=true
 
-        - name: Dotnet code style
-          run: dotnet build -c Debug -warnaserror Circle.Desktop.slnf -p:EnforceCodeStyleInBuild=true
+      - name: CodeFileSanity
+        run: |
+          # TODO: Add ignore filters and GitHub Workflow Command Reporting in CFS. That way we don't have to do this workaround.
+          # FIXME: Suppress warnings from templates project
+          exit_code=0
+          while read -r line; do
+            if [[ ! -z "$line" ]]; then
+              echo "::error::$line"
+              exit_code=1
+            fi
+          done <<< $(dotnet codefilesanity)
+          exit $exit_code
 
-        - name: CodeFileSanity
-          run: |
-            exit_code=0
-            while read -r line; do
-              if [[ ! -z "$line" ]]; then
-                echo "::error::$line"
-                exit_code=1
-              fi
-            done <<< $(dotnet codefilesanity)
-            exit $exit_code
+      - name: InspectCode
+        run: dotnet jb inspectcode $(pwd)/Circle.Desktop.slnf --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN
 
-        - name: InspectCode
-          run: dotnet jb inspectcode $(pwd)/Circle.Desktop.slnf --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN
-
-        - name: NVika
-          run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
+      - name: NVika
+        run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
 
   test:
     name: Test
     runs-on: ${{matrix.os.fullname}}
     env:
-      CIRCLE_EXECUTION_MODE: ${{matrix.threadingMode}}
+      OSU_EXECUTION_MODE: ${{matrix.threadingMode}}
     strategy:
        fail-fast: false
        matrix:
           os:
             - { prettyname: Windows, fullname: windows-latest }
-            - { prettyname: macOS, fullname: macos-latest }
+            # macOS runner performance has gotten unbearably slow so let's turn them off temporarily.
+            # - { prettyname: macOS, fullname: macos-latest }
+            - { prettyname: Linux, fullname: ubuntu-latest }
           threadingMode: ['SingleThread', 'MultiThreaded']
-    timeout-minutes: 60
+    timeout-minutes: 120
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Install .NET 6.0.x
-        uses: actions/setup-dotnet@v3
+      - name: Install .NET 8.0.x
+        uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: "6.0.x"
+          dotnet-version: "8.0.x"
 
       - name: Compile
         run: dotnet build -c Debug -warnaserror Circle.Desktop.slnf
 
       - name: Test
-        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"
-        shell: pwsh
+        run: >
+          dotnet test
+          Circle.Game.Tests/bin/Debug/**/Circle.Game.Tests.dll
+          Templates/**/*.Tests/bin/Debug/**/*.Tests.dll
+          --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"
+          --
+          NUnit.ConsoleOut=0
 
+      # Attempt to upload results even if test fails.
+      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always
       - name: Upload Test Results
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         if: ${{ always() }}
         with:
           name: Circle-test-results-${{matrix.os.prettyname}}-${{matrix.threadingMode}}
@@ -99,40 +105,40 @@ jobs:
     timeout-minutes: 60
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Install .NET 6.0.x
-        uses: actions/setup-dotnet@v3
+      - name: Setup JDK 11
+        uses: actions/setup-java@v4
         with:
-          dotnet-version: "6.0.x"
+          distribution: microsoft
+          java-version: 11
+
+      - name: Install .NET 8.0.x
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: "8.0.x"
 
       - name: Install .NET workloads
-        run: dotnet workload install maui-android
+        run: dotnet workload install android
 
       - name: Compile
         run: dotnet build -c Debug Circle.Android.slnf
 
   build-only-ios:
     name: Build only (iOS)
-    runs-on: macos-13
+    runs-on: macos-latest
     timeout-minutes: 60
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Set Xcode version
-        shell: bash
-        run: |
-          sudo xcode-select -s "/Applications/Xcode_14.3.app"
-          echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_14.3.app" >> $GITHUB_ENV
-
-      - name: Install .NET 6.0.x
-        uses: actions/setup-dotnet@v3
+      - name: Install .NET 8.0.x
+        uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: "6.0.x"
+          dotnet-version: "8.0.x"
 
       - name: Install .NET Workloads
-        run: dotnet workload install maui-ios
+        run: dotnet workload install ios --from-rollback-file https://raw.githubusercontent.com/ppy/osu-framework/refs/heads/master/workloads.json
 
       - name: Build
-        run: dotnet build -c Debug Circle.iOS
+        run: dotnet build -c Debug Circle.iOS.slnf
