Fix iOS build workflow failing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,62 @@
 on: [pull_request]
 name: Continuous Integration
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
+permissions:
+  contents: read # to fetch code (actions/checkout)
 
 jobs:
+  inspect-code:
+      name: Code Quality
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v3
+
+        - name: Install .NET 3.1.x LTS
+          uses: actions/setup-dotnet@v3
+          with:
+            dotnet-version: "3.1.x"
+
+        - name: Install .NET 6.0.x
+          uses: actions/setup-dotnet@v3
+          with:
+            dotnet-version: "6.0.x"
+
+        - name: Restore Tools
+          run: dotnet tool restore
+
+        - name: Restore Packages
+          run: dotnet restore Circle.Desktop.slnf
+
+        - name: Restore inspectcode cache
+        uses: actions/cache@v3
+        with:
+          path: ${{ github.workspace }}/inspectcode
+          key: inspectcode-${{ hashFiles('.config/dotnet-tools.json', '.github/workflows/ci.yml', 'Circle.sln*', 'Circle*.slnf', '.editorconfig', '.globalconfig', 'CodeAnalysis/*', '**/*.csproj', '**/*.props') }}
+
+        - name: Dotnet code style
+        run: dotnet build -c Debug -warnaserror Circle.Desktop.slnf -p:EnforceCodeStyleInBuild=true
+
+        - name: CodeFileSanity
+          run: |
+            exit_code=0
+            while read -r line; do
+              if [[ ! -z "$line" ]]; then
+                echo "::error::$line"
+                exit_code=1
+              fi
+            done <<< $(dotnet codefilesanity)
+            exit $exit_code
+
+        - name: InspectCode
+          run: dotnet jb inspectcode $(pwd)/Circle.Desktop.slnf --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN
+
+        - name: NVika
+          run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
+
   test:
     name: Test
     runs-on: ${{matrix.os.fullname}}
@@ -61,11 +116,17 @@ jobs:
   build-only-ios:
     if: false
     name: Build only (iOS)
-    runs-on: macos-latest
+    runs-on: macos-13
     timeout-minutes: 60
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+
+      - name: Set Xcode version
+        shell: bash
+        run: |
+          sudo xcode-select -s "/Applications/Xcode_14.3.app"
+          echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_14.3.app" >> $GITHUB_ENV
 
       - name: Install .NET 6.0.x
         uses: actions/setup-dotnet@v3
@@ -77,43 +138,3 @@ jobs:
 
       - name: Build
         run: dotnet build -c Debug Circle.iOS
-
-  inspect-code:
-    name: Code Quality
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Install .NET 3.1.x LTS
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: "3.1.x"
-
-      - name: Install .NET 6.0.x
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: "6.0.x"
-
-      - name: Restore Tools
-        run: dotnet tool restore
-
-      - name: Restore Packages
-        run: dotnet restore
-
-      - name: CodeFileSanity
-        run: |
-          exit_code=0
-          while read -r line; do
-            if [[ ! -z "$line" ]]; then
-              echo "::error::$line"
-              exit_code=1
-            fi
-          done <<< $(dotnet codefilesanity)
-          exit $exit_code
-
-      - name: InspectCode
-        run: dotnet jb inspectcode $(pwd)/Circle.Desktop.slnf --output=$(pwd)/inspectcodereport.xml --cachesDir=$(pwd)/inspectcode --verbosity=WARN
-
-      - name: NVika
-        run: dotnet nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
